### ISSUE TITLE
add new method to show all vid.cantidad group by Campo

### ISSUE THREAD

**Issue by Japoivvb** [corado-coder/Practica2Java#4]
1. after current showAllCampos() create a new method showCantidadVidByCampo()

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by corado-coder** [comment]
done

**Comment by Japoivvb** [comment]
1. ok, checked by code in #1 
2. ko
3. ko
4. ko
5. ok
