### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [corado-coder/Practica2Java#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by corado-coder** [comment]
![Captura de pantalla 2024-05-06 a las 16 56 37](https://github.com/corado-coder/Practica2Java/assets/124578825/df5610e0-313f-4a17-a13c-7f7214e3f41b)
![Captura de pantalla 2024-05-06 a las 16 56 44](https://github.com/corado-coder/Practica2Java/assets/124578825/5fa5dfbe-11da-46bc-b697-fd09fe051d36)
![Captura de pantalla 2024-05-06 a las 16 56 52](https://github.com/corado-coder/Practica2Java/assets/124578825/2dad3c47-b679-4415-8483-fc6fc0df06d9)
![Captura de pantalla 2024-05-06 a las 16 56 59](https://github.com/corado-coder/Practica2Java/assets/124578825/d29b8b98-2718-4c89-a79d-d5b2bb7c834a)

**Comment by Japoivvb** [comment]
commited after deadline, you must do other issue #8 to complete the UF3
